// Code generated by MockGen. DO NOT EDIT.
// Source: control_plane/internal/network/network.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	netlink "github.com/vishvananda/netlink"
)

// MockNetlinkManager is a mock of NetlinkManager interface.
type MockNetlinkManager struct {
	ctrl     *gomock.Controller
	recorder *MockNetlinkManagerMockRecorder
}

// MockNetlinkManagerMockRecorder is the mock recorder for MockNetlinkManager.
type MockNetlinkManagerMockRecorder struct {
	mock *MockNetlinkManager
}

// NewMockNetlinkManager creates a new mock instance.
func NewMockNetlinkManager(ctrl *gomock.Controller) *MockNetlinkManager {
	mock := &MockNetlinkManager{ctrl: ctrl}
	mock.recorder = &MockNetlinkManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetlinkManager) EXPECT() *MockNetlinkManagerMockRecorder {
	return m.recorder
}

// LinkAdd mocks base method.
func (m *MockNetlinkManager) LinkAdd(link netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAdd", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAdd indicates an expected call of LinkAdd.
func (mr *MockNetlinkManagerMockRecorder) LinkAdd(link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAdd", reflect.TypeOf((*MockNetlinkManager)(nil).LinkAdd), link)
}

// LinkByName mocks base method.
func (m *MockNetlinkManager) LinkByName(name string) (netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkByName", name)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkByName indicates an expected call of LinkByName.
func (mr *MockNetlinkManagerMockRecorder) LinkByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkByName", reflect.TypeOf((*MockNetlinkManager)(nil).LinkByName), name)
}

// LinkSetNsPid mocks base method.
func (m *MockNetlinkManager) LinkSetNsPid(link netlink.Link, pid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetNsPid", link, pid)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetNsPid indicates an expected call of LinkSetNsPid.
func (mr *MockNetlinkManagerMockRecorder) LinkSetNsPid(link, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetNsPid", reflect.TypeOf((*MockNetlinkManager)(nil).LinkSetNsPid), link, pid)
}
