// Code generated by MockGen. DO NOT EDIT.
// Source: /home/asuka/go/pkg/mod/github.com/vishvananda/netlink@v1.3.1/link.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	netlink "github.com/vishvananda/netlink"
)

// MockLink is a mock of Link interface.
type MockLink struct {
	ctrl     *gomock.Controller
	recorder *MockLinkMockRecorder
}

// MockLinkMockRecorder is the mock recorder for MockLink.
type MockLinkMockRecorder struct {
	mock *MockLink
}

// NewMockLink creates a new mock instance.
func NewMockLink(ctrl *gomock.Controller) *MockLink {
	mock := &MockLink{ctrl: ctrl}
	mock.recorder = &MockLinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLink) EXPECT() *MockLinkMockRecorder {
	return m.recorder
}

// Attrs mocks base method.
func (m *MockLink) Attrs() *netlink.LinkAttrs {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attrs")
	ret0, _ := ret[0].(*netlink.LinkAttrs)
	return ret0
}

// Attrs indicates an expected call of Attrs.
func (mr *MockLinkMockRecorder) Attrs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attrs", reflect.TypeOf((*MockLink)(nil).Attrs))
}

// Type mocks base method.
func (m *MockLink) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockLinkMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockLink)(nil).Type))
}

// MockLinkSlave is a mock of LinkSlave interface.
type MockLinkSlave struct {
	ctrl     *gomock.Controller
	recorder *MockLinkSlaveMockRecorder
}

// MockLinkSlaveMockRecorder is the mock recorder for MockLinkSlave.
type MockLinkSlaveMockRecorder struct {
	mock *MockLinkSlave
}

// NewMockLinkSlave creates a new mock instance.
func NewMockLinkSlave(ctrl *gomock.Controller) *MockLinkSlave {
	mock := &MockLinkSlave{ctrl: ctrl}
	mock.recorder = &MockLinkSlaveMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkSlave) EXPECT() *MockLinkSlaveMockRecorder {
	return m.recorder
}

// SlaveType mocks base method.
func (m *MockLinkSlave) SlaveType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlaveType")
	ret0, _ := ret[0].(string)
	return ret0
}

// SlaveType indicates an expected call of SlaveType.
func (mr *MockLinkSlaveMockRecorder) SlaveType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlaveType", reflect.TypeOf((*MockLinkSlave)(nil).SlaveType))
}
